### ISSUE TITLE
Last project is open even when opening a directory

### ISSUE THREAD

**Issue by jakubhruby** [danielmahon/atom-open-last-project#34]
# Steps to reproduce
1. open a project (in window 1)
2. open a different directory

## Expected result
- specified directory is opened as a new project (in window 2)

## Actual result
- last project from window 1 is opened instead

**Comment by danielmahon** [comment]
@jakubhruby are you still getting this? I cant reproduce. When I open a new project (different than in current window), it opens in the new window.

**Comment by jakubhruby** [comment]
It seems to be fixed, thanks.

**Comment by jakubhruby** [comment]
Well, it seems its back. It worked well for a while, but now it does not. Maybe some chache-related issues? Adding an animation:
![screen 04-13-2015 21-36-24](https://cloud.githubusercontent.com/assets/8798755/7124285/147a1188-e228-11e4-805f-e7728806bd23.gif)

**Comment by jakubhruby** [comment]
The bug occures even after upgrade to ATom 0.191.0

**Comment by sparkjames** [comment]
I see this bug as well, Atom 0.192.0 and open-last-project 0.4.1.

I can reproduce it by using the Github OS X app. You can right click on on a repo, choose "Open in Atom", and it will open a new Atom window but it loads the last project instead of the repo I chose.

The same thing happens with what Jak was originally saying, which I assume is dragging a folder from Finder into Atom. You expect it to open that folder, but instead it opens the last project.

**Comment by danielmahon** [comment]
Project is deprecated #44
